# Filterbank config
filterbank:
  n_filters: 64
  kernel_size: 16
  stride: 8
# Network config
masknet:
  in_chan: 64
  n_src: 2
  out_chan: 64
  bn_chan: 128
  hid_size: 128
  chunk_size: 250
  hop_size: 125
  n_repeats: 6
  mask_act: 'sigmoid'
  bidirectional: true
  dropout: 0
# Training config
training:
  exp_dir: exp/train_dprnntasnet_autoaug
  epochs: 600
  batch_size: 2
  num_workers: 0
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: !!float 1e-5
# Data config
data:
  train_dir: /jmain01/home/JAD007/txk02/aaa18-txk02/Datasets/asteroid/egs/librimix/ConvTasNet/data/wav8k/min/train-100/
  valid_dir: /jmain01/home/JAD007/txk02/aaa18-txk02/Datasets/asteroid/egs/librimix/ConvTasNet/data/wav8k/min/dev
  test_dir: /jmain01/home/JAD007/txk02/aaa18-txk02/Datasets/asteroid/egs/librimix/ConvTasNet/data/wav8k/min/test
  task: sep_noisy
  nondefault_nsrc: 2
  sample_rate: 8000
  mode: min
  segment: 2.0
controller:
  M: 8
  entropy_penalty: !!float 1e-5
